---
title: "サンプル・レポート"
author: "Taguchi"
date: '`r format(Sys.time(), "%Y/%m/%d %H:%M")`'
output:
  html_document:
    fig_caption: yes
    number_sections: yes
    theme: default
    toc: true
    toc_depth: 3
    md_extensions: -ascii_identifiers
  word_document:
    fig_caption: yes
    reference_docx: default
    toc: yes
params:
  arg01: AAA
  arg02: 111
  arg03: !r format(Sys.Date(), "%Y/%m/%d")
---
```{r setup, include=FALSE}
library(ggplot2)      # Graphic package
library(rmarkdown)
library(knitr)      
library(stringr)

options(scipen=100)

knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(eval = TRUE)
knitr::opts_chunk$set(tidy = TRUE)
knitr::opts_chunk$set(warning = TRUE)
knitr::opts_chunk$set(error = FALSE)
knitr::opts_chunk$set(message = FALSE)

Sys.setenv(tz="asia/tokyo")

```

# Markdownサンプル
## 本文

行内へのRコード埋め込み

今日は`r params$arg03` です

箇条書き

* 変数1: `r params$arg01`
* 変数2: `r params$arg02`


## グラフ
サンプルデータ(diamond)の箱ひげ図を表示

```{r}
graph_data <- ggplot(diamonds, aes(y=carat,x=cut, fill=cut))+geom_boxplot()
plot(graph_data)

```

## リンク
[R Markdown](http://rmarkdown.rstudio.com/)

[Qiita](https://qiita.com/tomotagwork/items/c92fb40a76f56ea16aa4)
